
name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/'*' 
  pull_request:
    branches:
    - master
    - develop  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
      
    - name: Package scripts
      run: |
        yarn install
        yarn lint
        yarn build
        yarn test
